spring.application.name=thymeleaf03

server.port = 3333

#DB details
spring.datasoure.driver-class-name =  com.mysql.cj.jdbc.Driver
spring.datasource.url =jdbc:mysql://localhost:3306/sudheer
spring.datasource.username = root
spring.datasource.password = root

#JPA details
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

spring.thymeleaf.cache=false
